Bag of Words (BOW) is a method to extract features from text documents. These features can be used for training machine learning algorithms. It creates a vocabulary of all the unique words occurring in all the documents in the training set.

In [81]:
import pandas as pd

In [82]:
df = pd.read_excel('Comments.xlsx')
df['Comment']

0                                  djfjkdfjkjkffdk edited
1       Faith has exhibited enthusiasm in taking on th...
2       He now has now understood the structure of gra...
3       The Intern was oriented on ICT setup and Infra...
4       The student was oriented on the organization s...
                              ...                        
3909    Intern managed to set up a monitoring tool on ...
3910    This was impressive work. The intern opened gr...
3911    The week went well. Students had a background ...
3912    It was best to attach the intern to an actual ...
3913    He managed to complete the task as expected. H...
Name: Comment, Length: 3914, dtype: object

In [83]:
import re 
import nltk
from nltk.corpus import stopwords 
import numpy
set(stopwords.words('english'))
def word_extraction(sentence):   
    ignore = ['a', "the", "is"]    
    words = re.sub("[^\w]", " ",  sentence).split()    
    cleaned_text = [w.lower() for w in words if w not in ignore]    
    return cleaned_text

In [84]:
def tokenize(sentences):    
    words = []    
    for sentence in sentences:        
        w = word_extraction(sentence)        
        words.extend(w)            
        words = sorted(list(set(words)))    
        return words

In [85]:
def generate_bow(allsentences):        
    vocab = tokenize(allsentences)    
    print("Word List for Document \n{0} \n".format(vocab))

In [86]:
allsentences = ["Joe waited for the train train", "The train was late", "Mary and Samantha took the bus"]

In [87]:
vocab = tokenize(allsentences)  

In [88]:
for sentence in allsentences:        
    words = word_extraction(sentence)        
    bag_vector = numpy.zeros(len(vocab))        
    for w in words:            
        for i,word in enumerate(vocab):                
            if word == w:                     
                bag_vector[i] += 1                            
                print("{0}\n{1}\n".format(sentence,numpy.array(bag_vector)))

Joe waited for the train train
[0. 1. 0. 0.]

Joe waited for the train train
[0. 1. 0. 1.]

Joe waited for the train train
[1. 1. 0. 1.]

Joe waited for the train train
[1. 1. 1. 1.]

Joe waited for the train train
[1. 1. 2. 1.]

The train was late
[0. 0. 1. 0.]

